export const canvasMoreActions = [
  { id: 'save-version', label: '保存当前版本', icon: 'Save' },
  { id: 'view-history', label: '查看历史版本', icon: 'History' },
  { id: 'restore-version', label: '恢复历史版本', icon: 'RotateCcw' },
  { id: 'export-json', label: '导出画布 (JSON)', icon: 'Download' },
  { id: 'import-json', label: '导入画布 (JSON)', icon: 'Upload' },
  { id: 'divider-1' },
  { id: 'clean-assets', label: '清理未使用资产', icon: 'Trash2' },
  { id: 'check-links', label: '检查断链资源', icon: 'Link2Off' },
  { id: 'auto-layout', label: '整理节点布局', icon: 'Layout' },
  { id: 'divider-2' },
  { id: 'view-logs', label: '查看操作日志', icon: 'ListOrdered' },
  { id: 'view-queue', label: '查看任务队列', icon: 'ListTodo' },
  { id: 'view-failed', label: '查看失败任务', icon: 'XOctagon' },
  { id: 'retry-failed', label: '一键重试失败', icon: 'RefreshCw' },
  { id: 'divider-3' },
  { id: 'health-check', label: '项目健康检查', icon: 'Activity' },
  { id: 'view-shortcuts', label: '快捷键说明', icon: 'Keyboard' },
];
